// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MoodEnum string

const (
	MoodEnumHAPPY       MoodEnum = "HAPPY"
	MoodEnumSAD         MoodEnum = "SAD"
	MoodEnumENERGETIC   MoodEnum = "ENERGETIC"
	MoodEnumCALM        MoodEnum = "CALM"
	MoodEnumMELANCHOLIC MoodEnum = "MELANCHOLIC"
	MoodEnumANGRY       MoodEnum = "ANGRY"
	MoodEnumRELAXED     MoodEnum = "RELAXED"
	MoodEnumFOCUSED     MoodEnum = "FOCUSED"
	MoodEnumUNKNOWN     MoodEnum = "UNKNOWN"
)

func (e *MoodEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MoodEnum(s)
	case string:
		*e = MoodEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for MoodEnum: %T", src)
	}
	return nil
}

type NullMoodEnum struct {
	MoodEnum MoodEnum `json:"mood_enum"`
	Valid    bool     `json:"valid"` // Valid is true if MoodEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMoodEnum) Scan(value interface{}) error {
	if value == nil {
		ns.MoodEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MoodEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMoodEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MoodEnum), nil
}

type VisibilityEnum string

const (
	VisibilityEnumPUBLIC    VisibilityEnum = "PUBLIC"
	VisibilityEnumFOLLOWERS VisibilityEnum = "FOLLOWERS"
	VisibilityEnumLINKONLY  VisibilityEnum = "LINK_ONLY"
	VisibilityEnumPRIVATE   VisibilityEnum = "PRIVATE"
)

func (e *VisibilityEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VisibilityEnum(s)
	case string:
		*e = VisibilityEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for VisibilityEnum: %T", src)
	}
	return nil
}

type NullVisibilityEnum struct {
	VisibilityEnum VisibilityEnum `json:"visibility_enum"`
	Valid          bool           `json:"valid"` // Valid is true if VisibilityEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisibilityEnum) Scan(value interface{}) error {
	if value == nil {
		ns.VisibilityEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VisibilityEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisibilityEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VisibilityEnum), nil
}

type ClothingItem struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	Category   string             `json:"category"`
	Colors     []byte             `json:"colors"`
	Brand      pgtype.Text        `json:"brand"`
	StyleTags  []byte             `json:"style_tags"`
	ImageUrl   pgtype.Text        `json:"image_url"`
	IsFavorite bool               `json:"is_favorite"`
	TimesWorn  int32              `json:"times_worn"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type DailyOutfitPick struct {
	UserID          uuid.UUID          `json:"user_id"`
	PickDate        pgtype.Date        `json:"pick_date"`
	OutfitID        uuid.UUID          `json:"outfit_id"`
	SpotifyContext  []byte             `json:"spotify_context"`
	WeatherSnapshot []byte             `json:"weather_snapshot"`
	Reason          pgtype.Text        `json:"reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Follow struct {
	FollowerID uuid.UUID          `json:"follower_id"`
	FolloweeID uuid.UUID          `json:"followee_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Gallery struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	CoverImageUrl pgtype.Text        `json:"cover_image_url"`
	IsPublic      bool               `json:"is_public"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type GalleryOutfit struct {
	ID        uuid.UUID          `json:"id"`
	GalleryID uuid.UUID          `json:"gallery_id"`
	OutfitID  uuid.UUID          `json:"outfit_id"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Item struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	OriginalImageUrl pgtype.Text        `json:"original_image_url"`
	CleanImageUrl    pgtype.Text        `json:"clean_image_url"`
	Name             pgtype.Text        `json:"name"`
	Category         pgtype.Text        `json:"category"`
	Subcategory      pgtype.Text        `json:"subcategory"`
	Brand            pgtype.Text        `json:"brand"`
	Colors           []string           `json:"colors"`
	Season           []string           `json:"season"`
	Occasion         pgtype.Text        `json:"occasion"`
	StyleTags        []string           `json:"style_tags"`
	Pattern          pgtype.Text        `json:"pattern"`
	Vibe             pgtype.Text        `json:"vibe"`
	Mood             pgtype.Text        `json:"mood"`
	Size             pgtype.Text        `json:"size"`
	Notes            pgtype.Text        `json:"notes"`
	WearCount        int32              `json:"wear_count"`
	LastWornAt       pgtype.Timestamptz `json:"last_worn_at"`
	Enriched         bool               `json:"enriched"`
	EnrichmentData   []byte             `json:"enrichment_data"`
	Embedding        interface{}        `json:"embedding"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Outfit struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Name            pgtype.Text        `json:"name"`
	PreviewImageUrl pgtype.Text        `json:"preview_image_url"`
	Occasion        pgtype.Text        `json:"occasion"`
	Season          pgtype.Text        `json:"season"`
	Vibe            pgtype.Text        `json:"vibe"`
	Mood            pgtype.Text        `json:"mood"`
	WeatherContext  pgtype.Text        `json:"weather_context"`
	SpotifyContext  []byte             `json:"spotify_context"`
	Source          string             `json:"source"`
	Rating          pgtype.Int4        `json:"rating"`
	WornAt          pgtype.Timestamptz `json:"worn_at"`
	WearCount       int32              `json:"wear_count"`
	Embedding       interface{}        `json:"embedding"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type OutfitItem struct {
	ID        uuid.UUID          `json:"id"`
	OutfitID  uuid.UUID          `json:"outfit_id"`
	ItemID    uuid.UUID          `json:"item_id"`
	Role      pgtype.Text        `json:"role"`
	Position  pgtype.Int4        `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OutfitLike struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	OutfitID  uuid.UUID          `json:"outfit_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OutfitShare struct {
	ID         uuid.UUID          `json:"id"`
	OutfitID   uuid.UUID          `json:"outfit_id"`
	OwnerID    uuid.UUID          `json:"owner_id"`
	Visibility VisibilityEnum     `json:"visibility"`
	ShareToken pgtype.Text        `json:"share_token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type SchemaMigration struct {
	Version string `json:"version"`
}

type ScrapedOutfit struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	ImageUrl     string             `json:"image_url"`
	Title        string             `json:"title"`
	Brand        pgtype.Text        `json:"brand"`
	Price        pgtype.Float8      `json:"price"`
	SourceUrl    string             `json:"source_url"`
	SourceDomain pgtype.Text        `json:"source_domain"`
	Category     pgtype.Text        `json:"category"`
	Tags         []string           `json:"tags"`
	MetaData     []byte             `json:"meta_data"`
	IsLiked      pgtype.Bool        `json:"is_liked"`
	SeenAt       pgtype.Timestamptz `json:"seen_at"`
	StyleTags    []string           `json:"style_tags"`
	WeatherTags  []string           `json:"weather_tags"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	SourceType   string             `json:"source_type"`
}

type SocialOutbox struct {
	ID          int64              `json:"id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type SpotifyTrack struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	SpotifyTrackID string             `json:"spotify_track_id"`
	TrackName      string             `json:"track_name"`
	ArtistName     string             `json:"artist_name"`
	AlbumName      pgtype.Text        `json:"album_name"`
	AlbumImageUrl  pgtype.Text        `json:"album_image_url"`
	PlayedAt       pgtype.Timestamptz `json:"played_at"`
	Valence        pgtype.Float8      `json:"valence"`
	Energy         pgtype.Float8      `json:"energy"`
	Danceability   pgtype.Float8      `json:"danceability"`
	Tempo          pgtype.Float8      `json:"tempo"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                    uuid.UUID          `json:"id"`
	Email                 pgtype.Text        `json:"email"`
	DisplayName           pgtype.Text        `json:"display_name"`
	AvatarUrl             pgtype.Text        `json:"avatar_url"`
	Mood                  MoodEnum           `json:"mood"`
	Location              pgtype.Text        `json:"location"`
	StyleIdentity         pgtype.Text        `json:"style_identity"`
	PreferredStyles       []string           `json:"preferred_styles"`
	PreferredColors       []string           `json:"preferred_colors"`
	PreferredStores       []string           `json:"preferred_stores"`
	BudgetMin             pgtype.Int4        `json:"budget_min"`
	BudgetMax             pgtype.Int4        `json:"budget_max"`
	TopsSize              pgtype.Text        `json:"tops_size"`
	BottomsSize           pgtype.Text        `json:"bottoms_size"`
	ShoesSize             pgtype.Text        `json:"shoes_size"`
	OuterwearSize         pgtype.Text        `json:"outerwear_size"`
	SpotifyID             pgtype.Text        `json:"spotify_id"`
	SpotifyAccessToken    pgtype.Text        `json:"spotify_access_token"`
	SpotifyRefreshToken   pgtype.Text        `json:"spotify_refresh_token"`
	SpotifyTokenExpiresAt pgtype.Timestamptz `json:"spotify_token_expires_at"`
	GoogleID              pgtype.Text        `json:"google_id"`
	GoogleAccessToken     pgtype.Text        `json:"google_access_token"`
	GoogleRefreshToken    pgtype.Text        `json:"google_refresh_token"`
	GoogleTokenExpiresAt  pgtype.Timestamptz `json:"google_token_expires_at"`
	GoogleCalendarID      pgtype.Text        `json:"google_calendar_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	RefreshTokenHash      pgtype.Text        `json:"refresh_token_hash"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
}
