// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxBatch = `-- name: ClaimOutboxBatch :many
SELECT id, occurred_at, event_type, payload
FROM social_outbox
WHERE processed_at IS NULL
ORDER BY id
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type ClaimOutboxBatchRow struct {
	ID         int64              `json:"id"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	EventType  string             `json:"event_type"`
	Payload    []byte             `json:"payload"`
}

// Claims a batch of unprocessed outbox rows for the projector to process.
// FOR UPDATE SKIP LOCKED lets multiple worker replicas run safely against the
// same outbox: each replica gets a disjoint set of rows and never blocks on
// another replica's batch.
func (q *Queries) ClaimOutboxBatch(ctx context.Context, limit int32) ([]ClaimOutboxBatchRow, error) {
	rows, err := q.db.Query(ctx, claimOutboxBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimOutboxBatchRow
	for rows.Next() {
		var i ClaimOutboxBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.EventType,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueOutboxEvent = `-- name: EnqueueOutboxEvent :exec
INSERT INTO social_outbox (event_type, payload)
VALUES ($1, $2)
`

type EnqueueOutboxEventParams struct {
	EventType string `json:"event_type"`
	Payload   []byte `json:"payload"`
}

func (q *Queries) EnqueueOutboxEvent(ctx context.Context, arg EnqueueOutboxEventParams) error {
	_, err := q.db.Exec(ctx, enqueueOutboxEvent, arg.EventType, arg.Payload)
	return err
}

const markOutboxProcessed = `-- name: MarkOutboxProcessed :exec
UPDATE social_outbox
SET processed_at = now()
WHERE id = ANY($1::bigint[])
`

func (q *Queries) MarkOutboxProcessed(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, markOutboxProcessed, dollar_1)
	return err
}
