// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*) FROM follows WHERE followee_id = $1
`

func (q *Queries) CountFollowers(ctx context.Context, followeeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowers, followeeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*) FROM follows WHERE follower_id = $1
`

func (q *Queries) CountFollowing(ctx context.Context, followerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowing, followerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO follows (follower_id, followee_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type FollowUserParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FollowerID, arg.FolloweeID)
	return err
}

const getFeedOutfits = `-- name: GetFeedOutfits :many
SELECT o.id, o.user_id, o.name, o.preview_image_url, o.occasion, o.season,
       o.vibe, o.mood, o.source, o.rating, o.worn_at, o.wear_count, o.created_at, o.updated_at
FROM outfits o
JOIN outfit_shares os ON os.outfit_id = o.id
LEFT JOIN follows f ON f.followee_id = o.user_id AND f.follower_id = $1
WHERE os.visibility IN ('PUBLIC', 'FOLLOWERS')
  AND (os.expires_at IS NULL OR os.expires_at > now())
  AND o.user_id != $1
ORDER BY (f.follower_id IS NOT NULL) DESC, o.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFeedOutfitsParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type GetFeedOutfitsRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Name            pgtype.Text        `json:"name"`
	PreviewImageUrl pgtype.Text        `json:"preview_image_url"`
	Occasion        pgtype.Text        `json:"occasion"`
	Season          pgtype.Text        `json:"season"`
	Vibe            pgtype.Text        `json:"vibe"`
	Mood            pgtype.Text        `json:"mood"`
	Source          string             `json:"source"`
	Rating          pgtype.Int4        `json:"rating"`
	WornAt          pgtype.Timestamptz `json:"worn_at"`
	WearCount       int32              `json:"wear_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFeedOutfits(ctx context.Context, arg GetFeedOutfitsParams) ([]GetFeedOutfitsRow, error) {
	rows, err := q.db.Query(ctx, getFeedOutfits, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedOutfitsRow
	for rows.Next() {
		var i GetFeedOutfitsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PreviewImageUrl,
			&i.Occasion,
			&i.Season,
			&i.Vibe,
			&i.Mood,
			&i.Source,
			&i.Rating,
			&i.WornAt,
			&i.WearCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowCounts = `-- name: GetFollowCounts :one
SELECT
    COALESCE(SUM(CASE WHEN f.followee_id = $1 THEN 1 ELSE 0 END), 0)::bigint AS followers_count,
    COALESCE(SUM(CASE WHEN f.follower_id = $1 THEN 1 ELSE 0 END), 0)::bigint AS following_count
FROM follows f
WHERE f.followee_id = $1 OR f.follower_id = $1
`

type GetFollowCountsRow struct {
	FollowersCount int64 `json:"followers_count"`
	FollowingCount int64 `json:"following_count"`
}

func (q *Queries) GetFollowCounts(ctx context.Context, followeeID uuid.UUID) (GetFollowCountsRow, error) {
	row := q.db.QueryRow(ctx, getFollowCounts, followeeID)
	var i GetFollowCountsRow
	err := row.Scan(&i.FollowersCount, &i.FollowingCount)
	return i, err
}

const getFollowers = `-- name: GetFollowers :many
SELECT u.id, u.email, u.display_name, u.avatar_url, u.spotify_id, u.created_at, u.updated_at
FROM users u
JOIN follows f ON f.follower_id = u.id
WHERE f.followee_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowersParams struct {
	FolloweeID uuid.UUID `json:"followee_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type GetFollowersRow struct {
	ID          uuid.UUID          `json:"id"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	SpotifyID   pgtype.Text        `json:"spotify_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFollowers(ctx context.Context, arg GetFollowersParams) ([]GetFollowersRow, error) {
	rows, err := q.db.Query(ctx, getFollowers, arg.FolloweeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowersRow
	for rows.Next() {
		var i GetFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.SpotifyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowing = `-- name: GetFollowing :many
SELECT u.id, u.email, u.display_name, u.avatar_url, u.spotify_id, u.created_at, u.updated_at
FROM users u
JOIN follows f ON f.followee_id = u.id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type GetFollowingParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

type GetFollowingRow struct {
	ID          uuid.UUID          `json:"id"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	SpotifyID   pgtype.Text        `json:"spotify_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetFollowing(ctx context.Context, arg GetFollowingParams) ([]GetFollowingRow, error) {
	rows, err := q.db.Query(ctx, getFollowing, arg.FollowerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowingRow
	for rows.Next() {
		var i GetFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.SpotifyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutfitByID = `-- name: GetOutfitByID :one
SELECT id, user_id, name, preview_image_url, occasion, season, vibe, mood,
       source, rating, worn_at, wear_count, created_at, updated_at
FROM outfits
WHERE id = $1 AND user_id = $2
`

type GetOutfitByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetOutfitByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Name            pgtype.Text        `json:"name"`
	PreviewImageUrl pgtype.Text        `json:"preview_image_url"`
	Occasion        pgtype.Text        `json:"occasion"`
	Season          pgtype.Text        `json:"season"`
	Vibe            pgtype.Text        `json:"vibe"`
	Mood            pgtype.Text        `json:"mood"`
	Source          string             `json:"source"`
	Rating          pgtype.Int4        `json:"rating"`
	WornAt          pgtype.Timestamptz `json:"worn_at"`
	WearCount       int32              `json:"wear_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetOutfitByID(ctx context.Context, arg GetOutfitByIDParams) (GetOutfitByIDRow, error) {
	row := q.db.QueryRow(ctx, getOutfitByID, arg.ID, arg.UserID)
	var i GetOutfitByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.PreviewImageUrl,
		&i.Occasion,
		&i.Season,
		&i.Vibe,
		&i.Mood,
		&i.Source,
		&i.Rating,
		&i.WornAt,
		&i.WearCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutfitShareByOutfitID = `-- name: GetOutfitShareByOutfitID :one
SELECT id, outfit_id, owner_id, visibility, share_token, expires_at, created_at, updated_at
FROM outfit_shares
WHERE outfit_id = $1
`

func (q *Queries) GetOutfitShareByOutfitID(ctx context.Context, outfitID uuid.UUID) (OutfitShare, error) {
	row := q.db.QueryRow(ctx, getOutfitShareByOutfitID, outfitID)
	var i OutfitShare
	err := row.Scan(
		&i.ID,
		&i.OutfitID,
		&i.OwnerID,
		&i.Visibility,
		&i.ShareToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutfitShareByToken = `-- name: GetOutfitShareByToken :one
SELECT id, outfit_id, owner_id, visibility, share_token, expires_at, created_at, updated_at
FROM outfit_shares
WHERE share_token = $1
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetOutfitShareByToken(ctx context.Context, shareToken pgtype.Text) (OutfitShare, error) {
	row := q.db.QueryRow(ctx, getOutfitShareByToken, shareToken)
	var i OutfitShare
	err := row.Scan(
		&i.ID,
		&i.OutfitID,
		&i.OwnerID,
		&i.Visibility,
		&i.ShareToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublicOutfitsByUser = `-- name: GetPublicOutfitsByUser :many
SELECT o.id, o.user_id, o.name, o.preview_image_url, o.occasion, o.season,
       o.vibe, o.mood, o.source, o.rating, o.worn_at, o.wear_count, o.created_at, o.updated_at
FROM outfits o
JOIN outfit_shares os ON os.outfit_id = o.id
WHERE o.user_id = $1
  AND os.visibility = 'PUBLIC'
  AND (os.expires_at IS NULL OR os.expires_at > now())
ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type GetPublicOutfitsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetPublicOutfitsByUserRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Name            pgtype.Text        `json:"name"`
	PreviewImageUrl pgtype.Text        `json:"preview_image_url"`
	Occasion        pgtype.Text        `json:"occasion"`
	Season          pgtype.Text        `json:"season"`
	Vibe            pgtype.Text        `json:"vibe"`
	Mood            pgtype.Text        `json:"mood"`
	Source          string             `json:"source"`
	Rating          pgtype.Int4        `json:"rating"`
	WornAt          pgtype.Timestamptz `json:"worn_at"`
	WearCount       int32              `json:"wear_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPublicOutfitsByUser(ctx context.Context, arg GetPublicOutfitsByUserParams) ([]GetPublicOutfitsByUserRow, error) {
	rows, err := q.db.Query(ctx, getPublicOutfitsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicOutfitsByUserRow
	for rows.Next() {
		var i GetPublicOutfitsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.PreviewImageUrl,
			&i.Occasion,
			&i.Season,
			&i.Vibe,
			&i.Mood,
			&i.Source,
			&i.Rating,
			&i.WornAt,
			&i.WearCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, avatar_url, spotify_id, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          uuid.UUID          `json:"id"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	SpotifyID   pgtype.Text        `json:"spotify_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.SpotifyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
    SELECT 1 FROM follows
    WHERE follower_id = $1 AND followee_id = $2
) AS is_following
`

type IsFollowingParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FolloweeID)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, display_name, avatar_url, spotify_id, created_at, updated_at
FROM users
WHERE id != $1
  AND (
    display_name ILIKE '%' || $2 || '%'
    OR email ILIKE '%' || $2 || '%'
  )
ORDER BY display_name
LIMIT $3
`

type SearchUsersParams struct {
	ID      uuid.UUID   `json:"id"`
	Column2 pgtype.Text `json:"column_2"`
	Limit   int32       `json:"limit"`
}

type SearchUsersRow struct {
	ID          uuid.UUID          `json:"id"`
	Email       pgtype.Text        `json:"email"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	SpotifyID   pgtype.Text        `json:"spotify_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.ID, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.SpotifyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM follows
WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowUserParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FolloweeID uuid.UUID `json:"followee_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FolloweeID)
	return err
}

const upsertOutfitShare = `-- name: UpsertOutfitShare :one
INSERT INTO outfit_shares (outfit_id, owner_id, visibility, share_token, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (outfit_id) DO UPDATE
SET visibility   = EXCLUDED.visibility,
    share_token  = EXCLUDED.share_token,
    expires_at   = EXCLUDED.expires_at,
    updated_at   = now()
RETURNING id, outfit_id, owner_id, visibility, share_token, expires_at, created_at, updated_at
`

type UpsertOutfitShareParams struct {
	OutfitID   uuid.UUID          `json:"outfit_id"`
	OwnerID    uuid.UUID          `json:"owner_id"`
	Visibility VisibilityEnum     `json:"visibility"`
	ShareToken pgtype.Text        `json:"share_token"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertOutfitShare(ctx context.Context, arg UpsertOutfitShareParams) (OutfitShare, error) {
	row := q.db.QueryRow(ctx, upsertOutfitShare,
		arg.OutfitID,
		arg.OwnerID,
		arg.Visibility,
		arg.ShareToken,
		arg.ExpiresAt,
	)
	var i OutfitShare
	err := row.Scan(
		&i.ID,
		&i.OutfitID,
		&i.OwnerID,
		&i.Visibility,
		&i.ShareToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
